# Generated by Django 4.2.6 on 2023-10-18 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Football_player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('Age', models.IntegerField()),
                ('DOB', models.CharField(max_length=10)),
                ('Jerseynumber', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
